---
openapi: 3.0.2
info:
  title: solsrv
  version: 1.0.0
  description: A simple document API for storing and retreiving documents
  termsOfService: http://swagger.io/terms/
  contact:
    name: Matthew Farrellee
    url: https://loopback.localhost
    email: matt@cs.wisc.edu
  license:
    name: GNU AGPLv3
    url: https://www.gnu.org/licenses/agpl.txt
paths:
  /documents:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Document'
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BulkAddResponse'
          description: Documents added
      operationId: solsrv.api.addDocuments
      summary: Add a set of documents to the repository
  /status:
    get:
      responses:
        200:
          content:
            application/json: {}
          description: Status
      operationId: solsrv.api.status
  /store:
    get:
      responses:
        200:
          content:
            application/json: {}
          description: ID Response
      operationId: solsrv.api.queryStoreIds
      summary: Get list of all keys in store
  /documents/{id}:
    get:
      parameters:
      - name: id
        description: Id of document to fetch
        schema:
          maxLength: 42
          type: string
        in: path
        required: true
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Document'
          description: Document response
        404:
          description: Document not found
      operationId: solsrv.api.getDocument
      summary: Get a specific document from the repository
      description: Return a document base on its id
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        200:
          description: Document added
        409:
          description: Document already exists
      operationId: solsrv.api.addDocument
      summary: Add a document to the repository
      description: Add a document to the repository. The user of this operation is
        required to provide the document's body and id. Duplicate ids are not allowed.
    parameters:
    - name: id
      schema:
        maxLength: 42
        type: string
      in: path
      required: true
components:
  schemas:
    Error:
      required:
      - code
      - message
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
    BulkAddResponse:
      description: ""
      type: object
      properties:
        accepted:
          description: ""
          type: array
          items:
            type: string
        rejected:
          description: ""
          type: array
          items:
            type: string
    Document:
      description: ""
      required:
      - id
      - content
      type: object
      properties:
        id:
          description: ""
          maxLength: 42
          type: string
        content:
          description: ""
          type: string
